### ISSUE TITLE
What version of fast.ai should i use? 

### ISSUE THREAD

**Issue by mpsampat** [jcreinhold/niftidataset#7]
Hi @jcreinhold ! 
Thanks for the great work and sharing this repo! 

I had a quick question. What version of fast.ai is this repo compatible with ? 
Can I Use fast.ai 1.0.57 for example ? 
thanks
Mehul

**Comment by jcreinhold** [comment]
Hey sorry for the late response. Unfortunately, I've not continued to test this package against new versions of the fastai package. I believe the last version I tested against was v1.0.41. You can try a newer version, but—as I recall—fastai's interface was constantly changing with breaking changes (which is why I stopped testing against it). 

Let me know if you do end up testing this with a newer version (like v1.0.57) and get errors. I'm not sure I'll bother supporting it, sorry to say, but if it is easy enough to fix I'll push a fix.

Re-open if you try something and get an error. Best of luck.
